# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'EasyShopper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyShopper
  pod 'Kingfisher', '~> 5.0'

  target 'EasyShopperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
